---
- name: ensure openstack nova controller requirements packages are installed
  action: "{{ openstack_nova_controller_package_info.pkg_mgr }}"
  args: openstack_nova_controller_package_info.args
  with_items: openstack_nova_controller_package_info.pre_pkgs
  when: openstack_nova_controller_package_info.pre_pkgs|length > 0

- name: ensure openstack repository is enabled
  action: "{{ openstack_nova_controller_repo_info.pkg_repo }}"
  args: openstack_nova_controller_repo_info.args
  with_items: openstack_nova_controller_repo_info.repos
  when: openstack_nova_controller_repo_info.repos|length > 0

- name: ensure openstack nova controller packages are installed
  action: "{{ openstack_nova_controller_package_info.pkg_mgr }}"
  args: openstack_nova_controller_package_info.args
  with_items: openstack_nova_controller_package_info.pkgs
  when: openstack_nova_controller_package_info.pkgs|length > 0

- name: ensure nova controller services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: openstack_nova_controller_services
  when: openstack_nova_controller_services|length > 0
