---
- include: mysql.yml

- include: rabbitmq.yml

- include: docker.yml
  when: nova_controller_dockerized_deployment

- include: install.yml
  when: not nova_controller_dockerized_deployment 

- include: configure.yml
  when: not nova_controller_dockerized_deployment 

- include: keystone.yml

- name: wait until nova controller service is ready
  wait_for:
    delay: 10
    host: "{{ openstack_compute_endpoint_host }}"
    port: 8774
    state: started
