---
- name: ensure nova database is present
  mysql_db:
    login_host: "{{ nova_mysql_host }}"
    login_port: "{{ nova_mysql_port }}"
    login_user: root
    login_password: "{{ nova_mysql_root_password }}"
    name: nova
  register: create_nova_db

- name: ensure nova database user is present
  mysql_user:
    login_host: "{{ nova_mysql_host }}"
    login_port: "{{ nova_mysql_port }}"
    login_user: root
    login_password: "{{ nova_mysql_root_password }}"
    name: nova
    host: "{{ item }}"
    password: "{{ nova_mysql_nova_password }}"
    priv: nova.*:ALL
  with_items:
    - localhost
    - "%"
